const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.LOS,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Anchor,
		C3.Behaviors.Platform,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{telaDoJogo: 0},
	{Sprite: 0},
	{Sólido: 0},
	{GRAMA1: 0},
	{GRAMA2: 0},
	{PlanoDeFundoEmBlocos: 0},
	{CampoDeVisão: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{Âncora: 0},
	{Floresta: 0},
	{Plataforma: 0},
	{explorer: 0},
	{Mouse: 0},
	{Teclado: 0},
	{GRAMA3: 0},
	{ESPINHO: 0},
	{MOEDA: 0},
	{Áudio: 0},
	{coração: 0},
	{textoX: 0},
	{Vidas: 0},
	{proximafase: 0},
	{RELÍQUIA: 0},
	{VCVENCEU: 0},
	{JOGARNOVAMENTE: 0},
	{SIM: 0},
	{NÃO: 0},
	{botao: 0},
	{THUNTERS: 0},
	{JOGAR: 0},
	{Texto: 0},
	{MORREU: 0},
	{Texto2: 0},
	{Vidas2: 0},
	{Vidas3: 0}
];

self.InstanceType = {
	telaDoJogo: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	GRAMA1: class extends self.ISpriteInstance {},
	GRAMA2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Floresta: class extends self.ITiledBackgroundInstance {},
	explorer: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	GRAMA3: class extends self.ISpriteInstance {},
	ESPINHO: class extends self.ISpriteInstance {},
	MOEDA: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	coração: class extends self.ISpriteInstance {},
	textoX: class extends self.ITextInstance {},
	Vidas: class extends self.ITextInstance {},
	proximafase: class extends self.ISpriteInstance {},
	RELÍQUIA: class extends self.ISpriteInstance {},
	VCVENCEU: class extends self.ITextInstance {},
	JOGARNOVAMENTE: class extends self.ITextInstance {},
	SIM: class extends self.ITextInstance {},
	NÃO: class extends self.ITextInstance {},
	botao: class extends self.ISpriteInstance {},
	THUNTERS: class extends self.ITextInstance {},
	JOGAR: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	MORREU: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {}
}